### ISSUE TITLE
Please make this repo private

### ISSUE THREAD

**Issue by bathal1** [Rub92/CS-328-EPFL#1]
Hello,
I am a teaching assistant at EPFL, in charge of teaching the numerical methods course.
This repository contains solutions to assignements of a course that is still being taught at EPFL. In an effort to reduce temptations to cheat for current students, we kindly ask you to make it private.

Best,
Baptiste

**Comment by Rub92** [comment]
Hello Baptiste,
I am Ruben, it is nice to meet you. I saw on your resume that you joined EPFL in 2020 for a PhD, congratulations and good luck for it as it is a long and hard process! 

These assignments were given to me in 2019, so a few months before you join EPFL. I think it is your responsibility, as you are in charge of teaching this class to renew the assignments rather than just using the one from the past years. And for the students that are able to find my repo, well they are acquiring a great skills required by nearly any advanced jobs (tech and non-tech), which is research. 

Happy to chat more about it. Feel free to reach out to me via email, cell or LinkedIn

Have a nice week
Ruben
